<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/home.css">
    <link rel="icon" type="img" href="/public/img/feliz.png">
    <title>be positive!</title>
</head>
<body>
    <div class="wrapper">
      <nav class="navbar"> 
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Service</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
      </nav>   
    </div>

            <form action="login" class= "box" method="POST">
              
               <h1>be positive!</h1>
               </br>
            <?php
            // somente dados que podem ser alterados
            echo 'Nome: '   . $_POST['name'] ;
            echo 'Senha: '  . $_POST['pass'] ;
            
            
            ?>
           <input type="submit" name="cad" value="Deletar"></br>
           <input type="submit" name="cad" value="Alterar">

            </form>
    
</body>
</html>